workflows:
  main:
    name: iOS Build Unsigned IPA
    max_build_duration: 120
    instance_type: mac_mini_m1    
    environment:
      xcode: latest
      flutter: stable

    scripts:
      - name: Build
        script: |
          # Build the iOS project
          xcodebuild -workspace Runner.xcworkspace -scheme Runner -configuration Release clean build CODE_SIGNING_ALLOWED=NO

      - name: Create IPA
        script: |
          # Create an unsigned IPA file
          xcodebuild -exportArchive -archivePath "build/Runner.xcarchive" -exportPath "build/Runner.ipa" -exportOptionsPlist exportOptions.plist
