import 'package:cloud_firestore/cloud_firestore.dart';

class DisasterT{
  final String name;
  String communityProf;
  String hazardProf;
  String elderHigh;
  String elderMed;
  String elderLow;
  String elderIndv;
  String childHigh;
  String childMed;
  String childLow;
  String childIndv;
  String hsEdHigh;
  String hsEdMed;
  String hsEdLow;
  String hsEdIndv;
  String linIsoHigh;
  String linIsoMed;
  String linIsoLow;
  String linIsoIndv;
  String pocHigh;
  String pocMed;
  String pocLow;
  String pocIndv;
  String lincHigh;
  String lincMed;
  String lincLow;
  String lincIndv;
  String nheHigh;
  String nheMed;
  String nheLow;
  String nheIndv;
  String housingHigh;
  String housingMed;
  String housingLow;
  String housingIndv;
  String schoolsHigh;
  String schoolsMed;
  String schoolsLow;
  String schoolsIndv;
  String hospHigh;
  String hospMed;
  String hospLow;
  String hospIndv;
  String wasteHigh;
  String wasteMed;
  String wasteLow;
  String wasteIndv;
  String elecHigh;
  String elecMed;
  String elecLow;
  String elecIndv;
  String waterHigh;
  String waterMed;
  String waterLow;
  String waterIndv;
  String wasteWaterHigh;
  String wasteWaterMed;
  String wasteWaterLow;
  String wasteWaterIndv;
  String essenHigh;
  String essenMed;
  String essenLow;
  String essenIndv;
  String readyGaps;
  String prevGaps;
  String mitiGaps;
  String summary;
  String recommendation;

  DisasterT({
    required this.name,
    required this.communityProf,
    required this.hazardProf,
    required this.elderHigh,
    required this.elderMed,
    required this.elderLow,
    required this.elderIndv,
    required this.childHigh,
    required this.childMed,
    required this.childLow,
    required this.childIndv,
    required this.hsEdHigh,
    required this.hsEdMed,
    required this.hsEdLow,
    required this.hsEdIndv,
    required this.linIsoHigh,
    required this.linIsoMed,
    required this.linIsoLow,
    required this.linIsoIndv,
    required this.pocHigh,
    required this.pocMed,
    required this.pocLow,
    required this.pocIndv,
    required this.lincHigh,
    required this.lincMed,
    required this.lincLow,
    required this.lincIndv,
    required this.nheHigh,
    required this.nheMed,
    required this.nheLow,
    required this.nheIndv,
    required this.housingHigh,
    required this.housingMed,
    required this.housingLow,
    required this.housingIndv,
    required this.schoolsHigh,
    required this.schoolsMed,
    required this.schoolsLow,
    required this.schoolsIndv,
    required this.hospHigh,
    required this.hospMed,
    required this.hospLow,
    required this.hospIndv,
    required this.wasteHigh,
    required this.wasteMed,
    required this.wasteLow,
    required this.wasteIndv,
    required this.elecHigh,
    required this.elecMed,
    required this.elecLow,
    required this.elecIndv,
    required this.waterHigh,
    required this.waterMed,
    required this.waterLow,
    required this.waterIndv,
    required this.wasteWaterHigh,
    required this.wasteWaterMed,
    required this.wasteWaterLow,
    required this.wasteWaterIndv,
    required this.essenHigh,
    required this.essenMed,
    required this.essenLow,
    required this.essenIndv,
    required this.readyGaps,
    required this.prevGaps,
    required this.mitiGaps,
    required this.summary,
    required this.recommendation,
  });

  static DisasterT convertDisasterDocument(DocumentSnapshot doc)
  {
    return DisasterT(name: '',
    communityProf: doc.get('communityProf'),
    hazardProf: doc.get('hazardProf'),
    elderHigh: doc.get('elderHigh'),
    elderMed: doc.get('elderMed'),
    elderLow: doc.get('elderLow'),
    elderIndv: doc.get('elderIndv'),
    childHigh: doc.get('childHigh'),
    childMed: doc.get('childMed'), 
    childLow: doc.get('childLow'),
    childIndv: doc.get('childIndv'),
    hsEdHigh: doc.get('hsEdHigh'),
    hsEdMed: doc.get('hsEdMed'),
    hsEdLow: doc.get('hsEdLow'),
    hsEdIndv: doc.get('hsEdIndv'),
    linIsoHigh: doc.get('linIsoHigh'),
    linIsoMed: doc.get('linIsoMed'),
    linIsoLow: doc.get('linIsoLow'),
    linIsoIndv: doc.get('linIsoIndv'),
    pocHigh: doc.get('pocHigh'),
    pocMed: doc.get('pocMed'),
    pocLow: doc.get('pocLow'),
    pocIndv: doc.get('pocIndv'),
    lincHigh: doc.get('lincHigh'),
    lincMed: doc.get('lincMed'),
    lincLow: doc.get('lincLow'),
    lincIndv: doc.get('lincIndv'),
    nheHigh: doc.get('nheHigh'),
    nheMed: doc.get('nheMed'),
    nheLow: doc.get('nheLow'),
    nheIndv: doc.get('nheIndv'),
    housingHigh: doc.get('housingHigh'),
    housingMed: doc.get('housingMed'), 
    housingLow: doc.get('housingLow'),
    housingIndv: doc.get('housingIndv'),
    schoolsHigh: doc.get('schoolsHigh'),
    schoolsMed: doc.get('schoolsMed'),
    schoolsLow: doc.get('schoolsLow'),
    schoolsIndv: doc.get('schoolsIndv'),
    hospHigh: doc.get('hospHigh'),
    hospMed: doc.get('hospMed'),
    hospLow: doc.get('hospLow'),
    hospIndv: doc.get('hospIndv'),
    wasteHigh: doc.get('wasteHigh'),
    wasteMed: doc.get('wasteMed'),
    wasteLow: doc.get('wasteLow'),
    wasteIndv: doc.get('wasteIndv'),
    elecHigh: doc.get('elecHigh'),
    elecMed: doc.get('elecMed'),
    elecLow: doc.get('elecLow'),
    elecIndv: doc.get('elecIndv'),
    waterHigh: doc.get('waterHigh'),
    waterMed: doc.get('waterMed'),
    waterLow: doc.get('waterLow'),
    waterIndv: doc.get('waterIndv'),
    wasteWaterHigh: doc.get('wasteWaterHigh'),
    wasteWaterMed: doc.get('wasteWaterMed'),
    wasteWaterLow: doc.get('wasteWaterLow'),
    wasteWaterIndv: doc.get('wasteWaterIndv'),
    essenHigh: doc.get('essenHigh'),
    essenMed: doc.get('essenMed'),
    essenLow: doc.get('essenLow'),
    essenIndv: doc.get('essenIndv'),
    readyGaps: doc.get('readyGaps'),
    prevGaps: doc.get('prevGaps'),
    mitiGaps: doc.get('mitiGaps'),
    summary: doc.get('summary'),
    recommendation: doc.get('recommendation')
    );
  }
}
