import 'package:cloud_firestore/cloud_firestore.dart';

class VulnerableT{
  final String name;
  String hazardProf;
  String popHigh;
  String popMed;
  String popLow;
  String elderHigh;
  String elderMed;
  String elderLow;
  String childHigh;
  String childMed;
  String childLow;
  String hsEdHigh;
  String hsEdMed;
  String hsEdLow;
  String linIsoHigh;
  String linIsoMed;
  String linIsoLow;
  String pocHigh;
  String pocMed;
  String pocLow;
  String lincHigh;
  String lincMed;
  String lincLow;
  String nheHigh;
  String nheMed;
  String nheLow;
  String housingHigh;
  String housingMed;
  String housingLow;
  String schoolsHigh;
  String schoolsMed;
  String schoolsLow;
  String hospHigh;
  String hospMed;
  String hospLow;
  String wasteHigh;
  String wasteMed;
  String wasteLow;
  String elecHigh;
  String elecMed;
  String elecLow;
  String waterHigh;
  String waterMed;
  String waterLow;
  String wasteWaterHigh;
  String wasteWaterMed;
  String wasteWaterLow;
  String essenHigh;
  String essenMed;
  String essenLow;
  String summary;

  VulnerableT({
    required this.name,
    required this.hazardProf,
    required this.popHigh,
    required this.popMed,
    required this.popLow,
    required this.elderHigh,
    required this.elderMed,
    required this.elderLow,
    required this.childHigh,
    required this.childMed,
    required this.childLow,
    required this.hsEdHigh,
    required this.hsEdMed,
    required this.hsEdLow,
    required this.linIsoHigh,
    required this.linIsoMed,
    required this.linIsoLow,
    required this.pocHigh,
    required this.pocMed,
    required this.pocLow,
    required this.lincHigh,
    required this.lincMed,
    required this.lincLow,
    required this.nheHigh,
    required this.nheMed,
    required this.nheLow,
    required this.housingHigh,
    required this.housingMed,
    required this.housingLow,
    required this.schoolsHigh,
    required this.schoolsMed,
    required this.schoolsLow,
    required this.hospHigh,
    required this.hospMed,
    required this.hospLow,
    required this.wasteHigh,
    required this.wasteMed,
    required this.wasteLow,
    required this.elecHigh,
    required this.elecMed,
    required this.elecLow,
    required this.waterHigh,
    required this.waterMed,
    required this.waterLow,
    required this.wasteWaterHigh,
    required this.wasteWaterMed,
    required this.wasteWaterLow,
    required this.essenHigh,
    required this.essenMed,
    required this.essenLow,
    required this.summary,
  });

  static VulnerableT convertVulnerabilityDocument(DocumentSnapshot doc)
  {
    return VulnerableT(
      name:        doc.get('name'),
      hazardProf:  doc.get('hazardProf'),
      popHigh:     doc.get('popHigh'),
      popMed:      doc.get('popMed'),
      popLow:      doc.get('popLow'),
      elderHigh:   doc.get('elderHigh'),
      elderMed:    doc.get('elderMed'),
      elderLow:    doc.get('elderLow'),
      childHigh:   doc.get('childHigh'),
      childMed:    doc.get('childMed'),
      childLow:    doc.get('childLow'),
      hsEdHigh:    doc.get('hsEdHigh'),
      hsEdMed:     doc.get('hsEdMed'),
      hsEdLow:     doc.get('hsEdLow'),
      linIsoHigh:  doc.get('linIsoHigh'),
      linIsoMed:   doc.get('linIsoMed'),
      linIsoLow:   doc.get('linIsoLow'),
      pocHigh:     doc.get('pocHigh'),
      pocMed:      doc.get('pocMed'),
      pocLow:      doc.get('pocLow'),
      lincHigh:    doc.get('lincHigh'),
      lincMed:     doc.get('lincMed'),
      lincLow:     doc.get('lincLow'),
      nheHigh:     doc.get('nheHigh'),
      nheMed:      doc.get('nheMed'),
      nheLow:      doc.get('nheLow'),
      housingHigh: doc.get('housingHigh'),
      housingMed:  doc.get('housingMed'),
      housingLow:  doc.get('housingLow'),
      schoolsHigh: doc.get('schoolsHigh'),
      schoolsMed:  doc.get('schoolsMed'),
      schoolsLow:  doc.get('schoolsLow'),
      hospHigh:    doc.get('hospHigh'),
      hospMed:     doc.get('hospMed'),
      hospLow:     doc.get('hospLow'),
      wasteHigh:   doc.get('wasteHigh'),
      wasteMed:    doc.get('wasteMed'),
      wasteLow:    doc.get('wasteLow'),
      elecHigh:    doc.get('elecHigh'),
      elecMed:     doc.get('elecMed'),
      elecLow:     doc.get('elecLow'),
      waterHigh:   doc.get('waterHigh'),
      waterMed:    doc.get('waterMed'),
      waterLow:    doc.get('waterLow'),
      wasteWaterHigh: doc.get('wasteWaterHigh'),
      wasteWaterMed: doc.get('wasteWaterMed'),
      wasteWaterLow: doc.get('wasteWaterLow'),
      essenHigh:    doc.get('essenHigh'),
      essenMed:     doc.get('essenMed'),
      essenLow:     doc.get('essenLow'),
      summary:      doc.get('summary')
      );
  }
}